### ISSUE TITLE
Add Ability to bypass redux altogether

### ISSUE THREAD

**Issue by jkusachi** [jkusachi/redux-offline-apollo-link#2]
In the event we want to not do anything with redux/redux-offline, we should have an option to bypass it completely

proposing 

```
{
...
   "skipRedux": true
...
} ?
```

then we can wrap all calls with it

**Comment by pragmaticivan** [comment]
Just adding, what about an option to skip only redux-offline? by using redux and returning the response of the observable/promise it would behave just fine if there is no retry?
